"""Initial tables for ticker statistics and industry aggregation

Revision ID: 43fe26fc895e
Revises: fda80b6a1a4f
Create Date: 2025-12-05 18:29:06.066133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43fe26fc895e'
down_revision: Union[str, Sequence[str], None] = 'fda80b6a1a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_aggregation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('avg_pe_ratio', sa.Float(), nullable=True),
    sa.Column('avg_revenue_growth', sa.Float(), nullable=True),
    sa.Column('sum_revenue', sa.Float(), nullable=True),
    sa.Column('ticker_count', sa.Integer(), nullable=True),
    sa.Column('calculation_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_aggregation_industry'), 'industry_aggregation', ['industry'], unique=True)
    op.create_table('ticker_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('net_income_ttm', sa.Float(), nullable=True),
    sa.Column('debt_ratio', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('earnings', sa.Float(), nullable=True),
    sa.Column('revenue_current', sa.Float(), nullable=True),
    sa.Column('revenue_previous', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('total_equity', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('data_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticker_statistics_industry'), 'ticker_statistics', ['industry'], unique=False)
    op.create_index(op.f('ix_ticker_statistics_symbol'), 'ticker_statistics', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_statistics_symbol'), table_name='ticker_statistics')
    op.drop_index(op.f('ix_ticker_statistics_industry'), table_name='ticker_statistics')
    op.drop_table('ticker_statistics')
    op.drop_index(op.f('ix_industry_aggregation_industry'), table_name='industry_aggregation')
    op.drop_table('industry_aggregation')
    # ### end Alembic commands ###
